# List of Telegram channels/groups to scrape
# Format: Each channel should be the username or full t.me link

# source: https://github.com/jackhawks/rectg/blob/main/README.md?plain=1
RECTG_CHANNELS = [
    "https://t.me/Aliyun_4K_Movies",
    "https://t.me/appmew",
    "https://t.me/telonews_cn",
    "https://t.me/Legado_Channels",
    "https://t.me/WenAnBa",
    "https://t.me/Lottery_home",
    "https://t.me/TGeBook",
    "https://t.me/Galgamer_Channel",
    "https://t.me/Qikan2023",
    "https://t.me/meizitu3",
    "https://t.me/MovieAnywhere",
    "https://t.me/bookusefor3",
    "https://t.me/jike_collection",
    "https://t.me/goworkbitch",
    "https://t.me/TVbox888",
    "https://t.me/theblockbeats",
    "https://t.me/AWAvenue",
    "https://t.me/wsj_rss",
    "https://t.me/privatetrackernews",
    "https://t.me/tastegirl",
    "https://t.me/xuehuashe",
    "https://t.me/peekfun",
    "https://t.me/ovov1234",
    "https://t.me/scitech_fans",
    "https://t.me/acgzhenghe",
    "https://t.me/jumpto22222",
    "https://t.me/chainnews",
    "https://t.me/LetITFlyW",
    "https://t.me/xqsranimegif",
    "https://t.me/useless_project_ideas",
    "https://t.me/jingxu6",
    "https://t.me/weibo_one",
    "https://t.me/wanmeihudu",
    "https://t.me/kawaii_collection",
    "https://t.me/HLWYS",
    "https://t.me/amazonhotevery",
    "https://t.me/lowendaff_blog",
    "https://t.me/nekosc",
    "https://t.me/awesomeopensource",
    "https://t.me/youshenggushi",
    "https://t.me/jin10light",
    "https://t.me/writing_discuss",
    "https://t.me/TinySnow4Yi",
    "https://t.me/mokeyjay_channel",
    "https://t.me/qiushibaike",
    "https://t.me/mytvseries",
    "https://t.me/exploreclassical",
    "https://t.me/AppleSpyder",
    "https://t.me/readingeventhosting",
    "https://t.me/Pwrtelegram",
    "https://t.me/gaomutongxue",
    "https://t.me/+rvCtIaOWZ1lmNmY1",
    "https://t.me/pythonzh",
    "https://t.me/nasfan",
    "https://t.me/AppleTVPlus",
    "https://t.me/cpluspluszh",
    "https://t.me/NewlearnerGroup",
    "https://t.me/zaprobest",
    "https://t.me/+rq848Z09nehlOTgx",
    "https://t.me/cosplaysharegroup",
    "https://t.me/zh_GV",
    "https://t.me/Clanguagezh",
    "https://t.me/BlockBeats_App",
    "https://t.me/P_Y_T_H_O_N",
    "https://t.me/flgirl",
    "https://t.me/cn_coupon",
    "https://t.me/NintendoSwitchCN",
    "https://t.me/ReadfineChat",
    "https://t.me/HiFiMusicResource",
    "https://t.me/AndroidDevCn",
    "https://t.me/lajilao",
    "https://t.me/simpreadgroup",
    "https://t.me/Moviemarket_group",
    "https://t.me/smms_images",
    "https://t.me/freemorebestchat",
    "https://t.me/CoolComic404_Fans",
    "https://t.me/raspicn",
    "https://t.me/FlutterCN",
    "https://t.me/gamecn",
    "https://t.me/manjarolinux_cn",
    "https://t.me/appleusergroup_tg",
    "https://t.me/fun_makers",
    "https://t.me/shoppingwdiscount",
    "https://t.me/+RDKqoTmhCmd2Q8g-",
    "https://t.me/chromebook_cn",
    "https://t.me/iOS1314",
    "https://t.me/joinchat/Gxp1thdP5FPRkmL2ftI5IA",
    "https://t.me/tos_unofficial",
    "https://t.me/+tLmbq7vP6BxiMjQ1",
    "https://t.me/nextnb",
    "https://t.me/+lE4aRgBXk0M0MDMx",
    "https://t.me/yxbymm",
    "https://t.me/icbcbot",
    "https://t.me/FengDoorBot",
    "https://t.me/ZUOLUOTV_AI_BOT",
    "https://t.me/DouYintg_bot",
    "https://t.me/bilibiliparse_bot",
    "https://t.me/tgLotteryBot",
    "https://t.me/GuangGaoShaShouBot",
    "https://t.me/areply_bot",
    "https://t.me/LotteryHelperBot",
    "https://t.me/fangzhang_bot",
    "https://t.me/ParsehubBot"
]


# Combine all channels if needed
ALL_CHANNELS = RECTG_CHANNELS





